dbt_github:
  target: dev
  outputs:
    dev:
      dataset: "{{ env_var('BIGQUERY_DATASET') }}_dev"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DBT_LOCAL_KEYFILE') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      type: bigquery

    
    prod:
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile_json: "{{ env_var('BIGQUERY_KEYFILE') | as_native }}"
      location: US
      method: service-account-json
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      type: bigquery 